#!/usr/bin/env bash

docker-destroy-all(){
  # Stop all containers
  containers=`docker ps -a -q`
  if [ -n "$containers" ] ; then
    docker stop $containers
  fi

  # Delete all containers
  containers=`docker ps -a -q`
  if [ -n "$containers" ]; then
    docker rm -f -v $containers
  fi

  # Delete all images
  images=`docker images -q -a`
  if [ -n "$images" ]; then
    docker rmi -f $images
  fi
}

# https://stackoverflow.com/a/30029855/823942
listening() {
    if [ $# -eq 0 ]; then
        sudo lsof -iTCP -sTCP:LISTEN -n -P
    elif [ $# -eq 1 ]; then
        sudo lsof -iTCP -sTCP:LISTEN -n -P | grep -i --color $1
    else
        echo "Usage: listening [pattern]"
    fi
}
